### ISSUE TITLE
вы двое - ненормальные. часть 1: теория

### ISSUE THREAD

**Issue by TheEE145** [Def-Try/parkour-mod#2]
я как профессионал в javascript скажу что вы самые ненормальные:
1. не читабельно, главное в коде - читабельность
2. всегда работайте с {} потому-что читабельно и вы можете понять\найти ошибку
3. let - локально, var - глобально. если вы оъявляете переменую в самом верху то используйте let.

надеюсь вы поняли что нельзя делать так как вы делали?

**Comment by Def-Try** [comment]
понял
